import { NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabaseAdmin";

export const runtime = "nodejs";
// ONE-TIME SEED — DELETE after running.

type MatRow = { name: string; default_unit: string; default_unit_cost: number; category: string };

const MATERIALS: MatRow[] = [
  // ── ARBORVITAE (BxB) ──────────────────────────────────────────────────
  { name: "Emerald Green Arborvitae 3-4'",                  default_unit: "ea", default_unit_cost: 57.00,  category: "Arborvitae" },
  { name: "Emerald Green Arborvitae 4-5'",                  default_unit: "ea", default_unit_cost: 69.00,  category: "Arborvitae" },
  { name: "Emerald Green Arborvitae 5-6'",                  default_unit: "ea", default_unit_cost: 87.00,  category: "Arborvitae" },
  { name: "Emerald Green Arborvitae 6-7'",                  default_unit: "ea", default_unit_cost: 117.00, category: "Arborvitae" },
  { name: "Emerald Green Arborvitae 7-8'",                  default_unit: "ea", default_unit_cost: 148.00, category: "Arborvitae" },
  { name: "Dark Green Arborvitae 3-4'",                     default_unit: "ea", default_unit_cost: 57.00,  category: "Arborvitae" },
  { name: "Dark Green Arborvitae 4-5'",                     default_unit: "ea", default_unit_cost: 69.00,  category: "Arborvitae" },
  { name: "Dark Green Arborvitae 5-6'",                     default_unit: "ea", default_unit_cost: 87.00,  category: "Arborvitae" },
  { name: "Dark Green Arborvitae 6-7'",                     default_unit: "ea", default_unit_cost: 117.00, category: "Arborvitae" },
  { name: "Dark Green Arborvitae 7-8'",                     default_unit: "ea", default_unit_cost: 148.00, category: "Arborvitae" },
  { name: "Green Giant Arborvitae 4-5'",                    default_unit: "ea", default_unit_cost: 80.00,  category: "Arborvitae" },
  { name: "Green Giant Arborvitae 5-6'",                    default_unit: "ea", default_unit_cost: 110.00, category: "Arborvitae" },
  { name: "Green Giant Arborvitae 6-7'",                    default_unit: "ea", default_unit_cost: 155.00, category: "Arborvitae" },
  { name: "Green Giant Arborvitae 7-8'",                    default_unit: "ea", default_unit_cost: 210.00, category: "Arborvitae" },
  { name: "Leprechaun Arborvitae 4-5'",                     default_unit: "ea", default_unit_cost: 80.00,  category: "Arborvitae" },
  // ── JUNIPER (BxB) ─────────────────────────────────────────────────────
  { name: "Upright Hetz Juniper 3-4'",                      default_unit: "ea", default_unit_cost: 88.00,  category: "Juniper" },
  { name: "Upright Hetz Juniper 4-5'",                      default_unit: "ea", default_unit_cost: 105.00, category: "Juniper" },
  { name: "Upright Hetz Juniper 5-6'",                      default_unit: "ea", default_unit_cost: 140.00, category: "Juniper" },
  { name: "Blue Arrow Juniper 4-5'",                        default_unit: "ea", default_unit_cost: 135.00, category: "Juniper" },
  { name: "Blue Arrow Juniper 5-6'",                        default_unit: "ea", default_unit_cost: 150.00, category: "Juniper" },
  { name: "Blue Point Juniper 3-4'",                        default_unit: "ea", default_unit_cost: 88.00,  category: "Juniper" },
  { name: "Blue Point Juniper 4-5'",                        default_unit: "ea", default_unit_cost: 106.00, category: "Juniper" },
  { name: "Blue Point Juniper 5-6'",                        default_unit: "ea", default_unit_cost: 140.00, category: "Juniper" },
  // ── YEW (BxB / Container) ─────────────────────────────────────────────
  { name: "Browni / Densiformis / Wardi Yew 12-15\"",       default_unit: "ea", default_unit_cost: 36.00,  category: "Yew" },
  { name: "Browni / Densiformis / Wardi Yew 15-18\"",       default_unit: "ea", default_unit_cost: 42.00,  category: "Yew" },
  { name: "Browni / Densiformis / Wardi Yew 18-24\"",       default_unit: "ea", default_unit_cost: 47.00,  category: "Yew" },
  { name: "Everlow Yew #7",                                  default_unit: "ea", default_unit_cost: 45.00,  category: "Yew" },
  { name: "Hicks Yew 15-18\"",                               default_unit: "ea", default_unit_cost: 42.00,  category: "Yew" },
  { name: "Hicks Yew 18-24\"",                               default_unit: "ea", default_unit_cost: 49.00,  category: "Yew" },
  { name: "Hicks Yew 24-30\"",                               default_unit: "ea", default_unit_cost: 59.00,  category: "Yew" },
  { name: "Brown / Dense / Wardi Yew #7 12-15\"",            default_unit: "ea", default_unit_cost: 36.00,  category: "Yew (Container)" },
  { name: "Brown / Dense / Wardi Yew #7 15-18\"",            default_unit: "ea", default_unit_cost: 42.00,  category: "Yew (Container)" },
  { name: "Brown / Dense / Wardi Yew #7 18-24\"",            default_unit: "ea", default_unit_cost: 47.00,  category: "Yew (Container)" },
  { name: "Everlow Yew #7 15-18\"",                          default_unit: "ea", default_unit_cost: 45.00,  category: "Yew (Container)" },
  { name: "Hicks Yew #7 15-18\"",                            default_unit: "ea", default_unit_cost: 42.00,  category: "Yew (Container)" },
  { name: "Hicks Yew #7 18-24\"",                            default_unit: "ea", default_unit_cost: 49.00,  category: "Yew (Container)" },
  { name: "Nova Yew #10 24-30\"",                             default_unit: "ea", default_unit_cost: 59.00,  category: "Yew (Container)" },
  // ── HEMLOCK ───────────────────────────────────────────────────────────
  { name: "Canadian Hemlock 5'",                             default_unit: "ea", default_unit_cost: 180.00, category: "Hemlock" },
  { name: "Canadian Hemlock 6'",                             default_unit: "ea", default_unit_cost: 215.00, category: "Hemlock" },
  // ── FIR ───────────────────────────────────────────────────────────────
  { name: "Canaan Fir 5-6'",                                 default_unit: "ea", default_unit_cost: 145.00, category: "Fir" },
  { name: "Canaan Fir 6-7'",                                 default_unit: "ea", default_unit_cost: 160.00, category: "Fir" },
  { name: "Concolor Fir 6-7'",                               default_unit: "ea", default_unit_cost: 240.00, category: "Fir" },
  { name: "Concolor Fir 7-8'",                               default_unit: "ea", default_unit_cost: 290.00, category: "Fir" },
  // ── PINE (BxB) ────────────────────────────────────────────────────────
  { name: "White Pine 4-5'",                                 default_unit: "ea", default_unit_cost: 123.00, category: "Pine" },
  { name: "White Pine 5-6'",                                 default_unit: "ea", default_unit_cost: 138.00, category: "Pine" },
  { name: "White Pine 6-7'",                                 default_unit: "ea", default_unit_cost: 225.00, category: "Pine" },
  // ── SPRUCE (BxB) ──────────────────────────────────────────────────────
  { name: "Colorado Blue Spruce 4-5'",                       default_unit: "ea", default_unit_cost: 128.00, category: "Spruce" },
  { name: "Colorado Blue Spruce 5-6'",                       default_unit: "ea", default_unit_cost: 143.00, category: "Spruce" },
  { name: "Colorado Blue Spruce 6-7'",                       default_unit: "ea", default_unit_cost: 160.00, category: "Spruce" },
  { name: "Colorado Blue Spruce 7-8'",                       default_unit: "ea", default_unit_cost: 180.00, category: "Spruce" },
  { name: "Black Hill / Norway / White Spruce 3-4'",         default_unit: "ea", default_unit_cost: 115.00, category: "Spruce" },
  { name: "Black Hill / Norway / White Spruce 4-5'",         default_unit: "ea", default_unit_cost: 123.00, category: "Spruce" },
  { name: "Black Hill / Norway / White Spruce 5-6'",         default_unit: "ea", default_unit_cost: 138.00, category: "Spruce" },
  { name: "Black Hill / Norway / White Spruce 6-7'",         default_unit: "ea", default_unit_cost: 155.00, category: "Spruce" },
  { name: "Black Hill / Norway / White Spruce 7-8'",         default_unit: "ea", default_unit_cost: 180.00, category: "Spruce" },
  { name: "Black Hill / Norway Spruce 6'",                   default_unit: "ea", default_unit_cost: 225.00, category: "Spruce" },
  { name: "Norway Spruce 7'",                                default_unit: "ea", default_unit_cost: 265.00, category: "Spruce" },
  { name: "Serbian Spruce 4-5'",                             default_unit: "ea", default_unit_cost: 128.00, category: "Spruce" },
  { name: "Serbian Spruce 5-6'",                             default_unit: "ea", default_unit_cost: 143.00, category: "Spruce" },
  { name: "Serbian Spruce 6-7'",                             default_unit: "ea", default_unit_cost: 160.00, category: "Spruce" },
  { name: "Park Grade Spruce 5-6'",                          default_unit: "ea", default_unit_cost: 105.00, category: "Spruce" },
  { name: "Park Grade Spruce 6-7'",                          default_unit: "ea", default_unit_cost: 120.00, category: "Spruce" },
  { name: "Park Grade Spruce 7-8'",                          default_unit: "ea", default_unit_cost: 138.00, category: "Spruce" },
  // ── CONTAINER ARBORVITAE ──────────────────────────────────────────────
  { name: "Emerald Green Arborvitae #7",                     default_unit: "ea", default_unit_cost: 36.00,  category: "Arborvitae (Container)" },
  { name: "Emerald Green Arborvitae #10",                    default_unit: "ea", default_unit_cost: 57.00,  category: "Arborvitae (Container)" },
  { name: "Fire Chief Arborvitae #3",                        default_unit: "ea", default_unit_cost: 35.00,  category: "Arborvitae (Container)" },
  { name: "Green Giant Arborvitae #10",                      default_unit: "ea", default_unit_cost: 57.00,  category: "Arborvitae (Container)" },
  { name: "Hetzi Midget Arborvitae #4",                      default_unit: "ea", default_unit_cost: 28.00,  category: "Arborvitae (Container)" },
  { name: "Mr. Bowling Ball Arborvitae #4",                  default_unit: "ea", default_unit_cost: 35.00,  category: "Arborvitae (Container)" },
  { name: "Whipcord Arborvitae #3",                          default_unit: "ea", default_unit_cost: 44.00,  category: "Arborvitae (Container)" },
  // ── CHAMAECYPARIS ─────────────────────────────────────────────────────
  { name: "Chamaecyparis Mops #5",                           default_unit: "ea", default_unit_cost: 40.00,  category: "Chamaecyparis" },
  { name: "Boulevard Chamaecyparis #6",                      default_unit: "ea", default_unit_cost: 97.00,  category: "Chamaecyparis" },
  { name: "Fernspray Gold Chamaecyparis #6",                 default_unit: "ea", default_unit_cost: 146.00, category: "Chamaecyparis" },
  { name: "Compact Hinoki Chamaecyparis 3-4'",               default_unit: "ea", default_unit_cost: 173.00, category: "Chamaecyparis" },
  { name: "Iseli Green Chamaecyparis #6",                    default_unit: "ea", default_unit_cost: 115.00, category: "Chamaecyparis" },
  { name: "Obtusa Compacta Chamaecyparis #6",                default_unit: "ea", default_unit_cost: 195.00, category: "Chamaecyparis" },
  { name: "Nootkatensis Pendula 7-8'",                       default_unit: "ea", default_unit_cost: 250.00, category: "Chamaecyparis" },
  { name: "Nootkatensis Pendula 8-9'",                       default_unit: "ea", default_unit_cost: 280.00, category: "Chamaecyparis" },
  // ── JUNIPER LOW / SPREADING ───────────────────────────────────────────
  { name: "Low Growing Juniper #4",                          default_unit: "ea", default_unit_cost: 27.50,  category: "Juniper – Low / Spreading" },
  { name: "Blue Star Juniper 15-18\"",                       default_unit: "ea", default_unit_cost: 35.00,  category: "Juniper – Low / Spreading" },
  // ── PINE CONTAINER ────────────────────────────────────────────────────
  { name: "Mugo Pine 12-15\"",                               default_unit: "ea", default_unit_cost: 30.00,  category: "Pine" },
  { name: "Mugo Pine 15-18\"",                               default_unit: "ea", default_unit_cost: 32.00,  category: "Pine" },
  { name: "Oregon Green Pine 4-5'",                          default_unit: "ea", default_unit_cost: 190.00, category: "Specialty Conifers" },
  { name: "Swiss Stone Pine 2.5-3'",                         default_unit: "ea", default_unit_cost: 140.00, category: "Specialty Conifers" },
  { name: "Vanderwolf Pine 4-5'",                            default_unit: "ea", default_unit_cost: 190.00, category: "Specialty Conifers" },
  { name: "Vanderwolf Pine 5-6'",                            default_unit: "ea", default_unit_cost: 270.00, category: "Specialty Conifers" },
  { name: "Vanderwolf Pine 6-7'",                            default_unit: "ea", default_unit_cost: 295.00, category: "Specialty Conifers" },
  // ── SPRUCE CONTAINER ──────────────────────────────────────────────────
  { name: "Alberta Spruce 24-30\"",                          default_unit: "ea", default_unit_cost: 52.00,  category: "Spruce (Container)" },
  { name: "Alberta Spruce 30-36\"",                          default_unit: "ea", default_unit_cost: 68.00,  category: "Spruce (Container)" },
  { name: "Alberta Spruce 36-42\"",                          default_unit: "ea", default_unit_cost: 98.00,  category: "Spruce (Container)" },
  { name: "Nest Spruce 12-15\"",                             default_unit: "ea", default_unit_cost: 31.00,  category: "Spruce (Container)" },
  { name: "Nest Spruce 15-18\"",                             default_unit: "ea", default_unit_cost: 35.00,  category: "Spruce (Container)" },
  { name: "Columnar Blue Spruce 3-4'",                       default_unit: "ea", default_unit_cost: 180.00, category: "Specialty Conifers" },
  { name: "Columnar Blue Spruce 4-5'",                       default_unit: "ea", default_unit_cost: 210.00, category: "Specialty Conifers" },
  { name: "Cupressina Spruce 6-7'",                          default_unit: "ea", default_unit_cost: 255.00, category: "Specialty Conifers" },
  { name: "Globe Blue Spruce 18-24\"",                       default_unit: "ea", default_unit_cost: 162.00, category: "Specialty Conifers" },
  { name: "Globe Blue Spruce 24-30\"",                       default_unit: "ea", default_unit_cost: 192.00, category: "Specialty Conifers" },
  { name: "Weeping Norway Spruce 4-5'",                      default_unit: "ea", default_unit_cost: 138.00, category: "Specialty Conifers" },
  { name: "Weeping Norway Spruce #10",                       default_unit: "ea", default_unit_cost: 290.00, category: "Specialty Conifers" },
  { name: "Weeping White Spruce #6",                         default_unit: "ea", default_unit_cost: 115.00, category: "Specialty Conifers" },
  { name: "Weeping White Spruce 5-6'",                       default_unit: "ea", default_unit_cost: 225.00, category: "Specialty Conifers" },
  // ── SHADE TREES ───────────────────────────────────────────────────────
  { name: "Ginkgo 1.75-2\"",                                 default_unit: "ea", default_unit_cost: 220.00, category: "Ginkgo" },
  { name: "Ginkgo 2-2.5\"",                                  default_unit: "ea", default_unit_cost: 320.00, category: "Ginkgo" },
  { name: "Hackberry 1.75-2\"",                              default_unit: "ea", default_unit_cost: 180.00, category: "Hackberry" },
  { name: "Hackberry 2-2.5\"",                               default_unit: "ea", default_unit_cost: 215.00, category: "Hackberry" },
  { name: "Hackberry 2.5-3\"",                               default_unit: "ea", default_unit_cost: 240.00, category: "Hackberry" },
  { name: "American Hornbeam 2\"",                           default_unit: "ea", default_unit_cost: 255.00, category: "Hornbeam" },
  { name: "American Hornbeam 1.75-2\"",                      default_unit: "ea", default_unit_cost: 230.00, category: "Hornbeam" },
  { name: "Columnar Hornbeam 2-2.5\"",                       default_unit: "ea", default_unit_cost: 305.00, category: "Hornbeam" },
  { name: "Greenspire / Sterling Silver Linden 1.75-2\"",    default_unit: "ea", default_unit_cost: 190.00, category: "Linden" },
  { name: "Linden 2-2.5\"",                                  default_unit: "ea", default_unit_cost: 235.00, category: "Linden" },
  { name: "Linden 2.5-3\"",                                  default_unit: "ea", default_unit_cost: 270.00, category: "Linden" },
  { name: "Skyline Locust 1.75-2\"",                         default_unit: "ea", default_unit_cost: 183.00, category: "Locust" },
  { name: "Skyline Locust 2-2.5\"",                          default_unit: "ea", default_unit_cost: 230.00, category: "Locust" },
  { name: "Skyline Locust 2.5-3\"",                          default_unit: "ea", default_unit_cost: 265.00, category: "Locust" },
  { name: "Sunburst Locust 1.75-2\"",                        default_unit: "ea", default_unit_cost: 183.00, category: "Locust" },
  { name: "Armstrong Gold Maple 2-2.5\"",                    default_unit: "ea", default_unit_cost: 230.00, category: "Maple" },
  { name: "Armstrong Gold Maple 2.5-3\"",                    default_unit: "ea", default_unit_cost: 265.00, category: "Maple" },
  { name: "Crimson King Maple 1.75-2\"",                     default_unit: "ea", default_unit_cost: 188.00, category: "Maple" },
  { name: "Crimson King Maple 2-2.5\"",                      default_unit: "ea", default_unit_cost: 240.00, category: "Maple" },
  { name: "Crimson King Maple 2.5-3\"",                      default_unit: "ea", default_unit_cost: 270.00, category: "Maple" },
  { name: "Crimson Sunset Maple 1.75-2\"",                   default_unit: "ea", default_unit_cost: 188.00, category: "Maple" },
  { name: "Crimson Sunset Maple 3\"",                        default_unit: "ea", default_unit_cost: 350.00, category: "Maple" },
  { name: "Emerald Lustre Maple 2.5-3\"",                    default_unit: "ea", default_unit_cost: 265.00, category: "Maple" },
  { name: "Sugar Maple 1.75-2\"",                            default_unit: "ea", default_unit_cost: 188.00, category: "Maple" },
  { name: "Sugar Maple 2-2.5\"",                             default_unit: "ea", default_unit_cost: 240.00, category: "Maple" },
  { name: "Sugar Maple 2.5-3\"",                             default_unit: "ea", default_unit_cost: 275.00, category: "Maple" },
  { name: "Autumn Blaze Maple 1.75-2\"",                     default_unit: "ea", default_unit_cost: 183.00, category: "Maple" },
  { name: "Autumn Blaze Maple 2-2.5\"",                      default_unit: "ea", default_unit_cost: 230.00, category: "Maple" },
  { name: "Autumn Blaze Maple 2.5-3\"",                      default_unit: "ea", default_unit_cost: 265.00, category: "Maple" },
  { name: "Autumn Blaze Maple 3-3.5\"",                      default_unit: "ea", default_unit_cost: 305.00, category: "Maple" },
  { name: "Autumn Blaze Maple 3.5-4\"",                      default_unit: "ea", default_unit_cost: 355.00, category: "Maple" },
  { name: "Autumn Blaze Maple Clump 10-12'",                 default_unit: "ea", default_unit_cost: 230.00, category: "Maple" },
  { name: "Autumn Blaze Maple Clump 14-16'",                 default_unit: "ea", default_unit_cost: 275.00, category: "Maple" },
  { name: "River Birch 7-8'",                                default_unit: "ea", default_unit_cost: 182.00, category: "Birch" },
  { name: "River Birch 8-10'",                               default_unit: "ea", default_unit_cost: 205.00, category: "Birch" },
  { name: "River Birch 10-12'",                              default_unit: "ea", default_unit_cost: 230.00, category: "Birch" },
  { name: "Frontier / Triumph Elm 2-2.5\"",                  default_unit: "ea", default_unit_cost: 225.00, category: "Elm" },
  { name: "Elm 2.5-3\"",                                     default_unit: "ea", default_unit_cost: 255.00, category: "Elm" },
  { name: "Elm 3-3.5\"",                                     default_unit: "ea", default_unit_cost: 285.00, category: "Elm" },
  { name: "Oak 1.75-2\"",                                    default_unit: "ea", default_unit_cost: 190.00, category: "Oak" },
  { name: "Oak 2-2.5\"",                                     default_unit: "ea", default_unit_cost: 235.00, category: "Oak" },
  { name: "Oak 2.5-3\"",                                     default_unit: "ea", default_unit_cost: 270.00, category: "Oak" },
  { name: "Kindred Spirit Oak 2\"",                          default_unit: "ea", default_unit_cost: 285.00, category: "Oak" },
  { name: "Ivory Silk Lilac Tree 1.75-2\"",                  default_unit: "ea", default_unit_cost: 225.00, category: "Other Shade Trees" },
  { name: "Ivory Silk Lilac Tree 2\"",                       default_unit: "ea", default_unit_cost: 265.00, category: "Other Shade Trees" },
  { name: "Coffee Tree 2-2.5\"",                             default_unit: "ea", default_unit_cost: 230.00, category: "Other Shade Trees" },
  { name: "Coffee Tree 2.5-3\"",                             default_unit: "ea", default_unit_cost: 265.00, category: "Other Shade Trees" },
  { name: "Slender Silhouette Sweetgum 2\"",                 default_unit: "ea", default_unit_cost: 285.00, category: "Other Shade Trees" },
  { name: "Tulip Tree 2\"",                                  default_unit: "ea", default_unit_cost: 275.00, category: "Other Shade Trees" },
  { name: "Northern Splendor Black Gum 2-2.5\"",             default_unit: "ea", default_unit_cost: 295.00, category: "Other Shade Trees" },
  { name: "Exclamation Sycamore 2-2.5\"",                    default_unit: "ea", default_unit_cost: 230.00, category: "Other Shade Trees" },
  { name: "Exclamation Sycamore 2.5-3\"",                    default_unit: "ea", default_unit_cost: 265.00, category: "Other Shade Trees" },
  // ── ORNAMENTAL TREES ──────────────────────────────────────────────────
  { name: "Serviceberry (Amelanchier) 4-5'",                 default_unit: "ea", default_unit_cost: 130.00, category: "Serviceberry" },
  { name: "Serviceberry (Amelanchier) 5-6'",                 default_unit: "ea", default_unit_cost: 158.00, category: "Serviceberry" },
  { name: "Serviceberry (Amelanchier) 6-7'",                 default_unit: "ea", default_unit_cost: 180.00, category: "Serviceberry" },
  { name: "Serviceberry (Amelanchier) 7-8'",                 default_unit: "ea", default_unit_cost: 215.00, category: "Serviceberry" },
  { name: "Serviceberry (Amelanchier) 8-9'",                 default_unit: "ea", default_unit_cost: 255.00, category: "Serviceberry" },
  { name: "Serviceberry Tree Form 1.75-2\"",                 default_unit: "ea", default_unit_cost: 170.00, category: "Serviceberry" },
  { name: "Serviceberry Tree Form 2-2.5\"",                  default_unit: "ea", default_unit_cost: 195.00, category: "Serviceberry" },
  { name: "Higan / Snow Fountain Cherry 1.75-2\"",           default_unit: "ea", default_unit_cost: 163.00, category: "Cherry" },
  { name: "Cherry 2-2.5\"",                                  default_unit: "ea", default_unit_cost: 185.00, category: "Cherry" },
  { name: "Washington Hawthorn Tree 2-2.5\"",                default_unit: "ea", default_unit_cost: 178.00, category: "Other Shade Trees" },
  { name: "Redbud Clump 5-6'",                               default_unit: "ea", default_unit_cost: 170.00, category: "Redbud" },
  { name: "Redbud Clump 6-7'",                               default_unit: "ea", default_unit_cost: 195.00, category: "Redbud" },
  { name: "Redbud Clump 7-8'",                               default_unit: "ea", default_unit_cost: 255.00, category: "Redbud" },
  { name: "Redbud Tree Form 1.5-1.75\"",                     default_unit: "ea", default_unit_cost: 168.00, category: "Redbud" },
  { name: "Redbud Tree Form 1.75-2\"",                       default_unit: "ea", default_unit_cost: 190.00, category: "Redbud" },
  { name: "Redbud Tree Form 2\"",                            default_unit: "ea", default_unit_cost: 275.00, category: "Redbud" },
  { name: "Dawn Redwood 2.5-3\"",                            default_unit: "ea", default_unit_cost: 245.00, category: "Other Shade Trees" },
  // ── DOGWOOD ───────────────────────────────────────────────────────────
  { name: "Kousa Dogwood 5-6'",                              default_unit: "ea", default_unit_cost: 172.00, category: "Dogwood" },
  { name: "Kousa Dogwood 6-7'",                              default_unit: "ea", default_unit_cost: 195.00, category: "Dogwood" },
  { name: "Kousa Dogwood 7-8'",                              default_unit: "ea", default_unit_cost: 240.00, category: "Dogwood" },
  { name: "Kousa Dogwood 8-9'",                              default_unit: "ea", default_unit_cost: 268.00, category: "Dogwood" },
  { name: "Scarlet Fire Dogwood Tree 1.5-1.75\"",            default_unit: "ea", default_unit_cost: 268.00, category: "Dogwood" },
  { name: "Stellar Pink Dogwood Tree 1.75-2\"",              default_unit: "ea", default_unit_cost: 295.00, category: "Dogwood" },
  // ── PEAR ──────────────────────────────────────────────────────────────
  { name: "Cleveland Select Pear 1.75-2\"",                  default_unit: "ea", default_unit_cost: 168.00, category: "Pear" },
  { name: "Cleveland Select Pear 2-2.5\"",                   default_unit: "ea", default_unit_cost: 190.00, category: "Pear" },
  { name: "Cleveland Select Pear 2.5-3\"",                   default_unit: "ea", default_unit_cost: 220.00, category: "Pear" },
  { name: "Cleveland Select Pear 3-3.5\"",                   default_unit: "ea", default_unit_cost: 255.00, category: "Pear" },
  // ── FLOWERING CRAB ────────────────────────────────────────────────────
  { name: "Flowering Crab 1.5-1.75\"",                       default_unit: "ea", default_unit_cost: 130.00, category: "Flowering Crab" },
  { name: "Flowering Crab 1.75-2\"",                         default_unit: "ea", default_unit_cost: 150.00, category: "Flowering Crab" },
  { name: "Flowering Crab 2-2.5\"",                          default_unit: "ea", default_unit_cost: 168.00, category: "Flowering Crab" },
  { name: "Flowering Crab 2.5-3\"",                          default_unit: "ea", default_unit_cost: 188.00, category: "Flowering Crab" },
  { name: "Multi Stem Crab 6-7'",                            default_unit: "ea", default_unit_cost: 152.00, category: "Flowering Crab" },
  { name: "Multi Stem Crab 7-8'",                            default_unit: "ea", default_unit_cost: 165.00, category: "Flowering Crab" },
  { name: "Dwarf / Weeping Crab 1.5-1.75\"",                default_unit: "ea", default_unit_cost: 145.00, category: "Flowering Crab" },
  { name: "Louisa Weeping Crab 1.75-2\"",                   default_unit: "ea", default_unit_cost: 148.00, category: "Flowering Crab" },
  { name: "Louisa Weeping Crab 2-2.5\"",                    default_unit: "ea", default_unit_cost: 168.00, category: "Flowering Crab" },
  { name: "Sargent / Sargent Tina Crab 1.25-1.5\"",         default_unit: "ea", default_unit_cost: 125.00, category: "Flowering Crab" },
  { name: "Sargent Crab 1.5-1.75\"",                        default_unit: "ea", default_unit_cost: 145.00, category: "Flowering Crab" },
  { name: "Sargent Crab 1.75-2\"",                          default_unit: "ea", default_unit_cost: 160.00, category: "Flowering Crab" },
  { name: "Sargent Crab 2-2.5\"",                           default_unit: "ea", default_unit_cost: 170.00, category: "Flowering Crab" },
  // Container Crabs
  { name: "Coralburst Crab #15",                             default_unit: "ea", default_unit_cost: 89.00,  category: "Flowering Crab" },
  { name: "Lollipop Crab #15",                               default_unit: "ea", default_unit_cost: 89.00,  category: "Flowering Crab" },
  { name: "Louisa Weeping Crab #15",                         default_unit: "ea", default_unit_cost: 90.00,  category: "Flowering Crab" },
  { name: "Prairie Fire Crab #15",                           default_unit: "ea", default_unit_cost: 83.00,  category: "Flowering Crab" },
  { name: "Red Barron Crab #15",                             default_unit: "ea", default_unit_cost: 83.00,  category: "Flowering Crab" },
  { name: "Red Jewel Crab #15",                              default_unit: "ea", default_unit_cost: 83.00,  category: "Flowering Crab" },
  { name: "Royal Raindrops Crab #15",                        default_unit: "ea", default_unit_cost: 83.00,  category: "Flowering Crab" },
  { name: "Sargent Tina Crab #15",                           default_unit: "ea", default_unit_cost: 89.00,  category: "Flowering Crab" },
  // Container ornamental trees
  { name: "Snow Fountain Cherry 6-7'",                       default_unit: "ea", default_unit_cost: 98.00,  category: "Cherry" },
  { name: "Cleveland Select Pear Container 6-7'",            default_unit: "ea", default_unit_cost: 98.00,  category: "Pear" },
  { name: "Dwarf Lilac Standard #7/#10",                     default_unit: "ea", default_unit_cost: 108.00, category: "Other Shade Trees" },
  { name: "Hibiscus Tree Form #6",                           default_unit: "ea", default_unit_cost: 120.00, category: "Other Shade Trees" },
  { name: "Hydrangea Tree Form #10",                         default_unit: "ea", default_unit_cost: 113.00, category: "Other Shade Trees" },
  { name: "Styrax Nightfall #15",                            default_unit: "ea", default_unit_cost: 135.00, category: "Other Shade Trees" },
  { name: "Dappled Willow Tree #6",                          default_unit: "ea", default_unit_cost: 98.00,  category: "Other Shade Trees" },
  // Container Maples
  { name: "Crimson Sunset Maple Container 1-1.25\"",         default_unit: "ea", default_unit_cost: 132.00, category: "Maple" },
  { name: "Green Mountain Sugar Maple Container 1-1.25\"",   default_unit: "ea", default_unit_cost: 132.00, category: "Maple" },
  { name: "Redpointe Maple Container 1-1.25\"",              default_unit: "ea", default_unit_cost: 132.00, category: "Maple" },
  // Fruit Trees
  { name: "Honeycrisp Apple #10",                            default_unit: "ea", default_unit_cost: 135.00, category: "Other Shade Trees" },
  { name: "Redhaven Peach #10",                              default_unit: "ea", default_unit_cost: 135.00, category: "Other Shade Trees" },
  // ── SHRUBS BxB ────────────────────────────────────────────────────────
  { name: "Burning Bush 18-24\"",                            default_unit: "ea", default_unit_cost: 33.00,  category: "Euonymus" },
  { name: "Burning Bush 24-30\"",                            default_unit: "ea", default_unit_cost: 35.00,  category: "Euonymus" },
  { name: "Forsythia BxB 2-2.5'",                            default_unit: "ea", default_unit_cost: 29.50,  category: "Forsythia" },
  { name: "Forsythia BxB 2.5-3'",                            default_unit: "ea", default_unit_cost: 34.50,  category: "Forsythia" },
  { name: "Dwarf / Korean / Miss Kim Lilac 18-24\"",         default_unit: "ea", default_unit_cost: 32.00,  category: "Lilac" },
  { name: "Dwarf Lilac 24-30\"",                             default_unit: "ea", default_unit_cost: 35.00,  category: "Lilac" },
  { name: "French Lilac BxB 2-2.5'",                         default_unit: "ea", default_unit_cost: 31.00,  category: "Lilac" },
  { name: "French Lilac BxB 2.5-3'",                         default_unit: "ea", default_unit_cost: 35.00,  category: "Lilac" },
  { name: "French Lilac BxB 3-4'",                           default_unit: "ea", default_unit_cost: 38.00,  category: "Lilac" },
  { name: "Chicago Lustre / Mohican Viburnum 2.5-3'",        default_unit: "ea", default_unit_cost: 35.00,  category: "Viburnum" },
  { name: "Viburnum BxB 3-4'",                               default_unit: "ea", default_unit_cost: 37.00,  category: "Viburnum" },
  { name: "Mariesii Viburnum #10",                           default_unit: "ea", default_unit_cost: 35.00,  category: "Viburnum" },
  { name: "Trilobum Viburnum 2.5-3'",                        default_unit: "ea", default_unit_cost: 35.00,  category: "Viburnum" },
  // ── CONTAINER DECIDUOUS SHRUBS ────────────────────────────────────────
  { name: "Red Aronia #4",                                   default_unit: "ea", default_unit_cost: 31.50,  category: "Aronia" },
  { name: "Low Scape Aronia #3",                             default_unit: "ea", default_unit_cost: 31.50,  category: "Aronia" },
  { name: "Barberry 15-18\"",                                default_unit: "ea", default_unit_cost: 30.00,  category: "Barberry" },
  { name: "Ivory Halo Dogwood #4",                           default_unit: "ea", default_unit_cost: 30.00,  category: "Dogwood Shrub" },
  { name: "Ivory Halo Dogwood #10",                          default_unit: "ea", default_unit_cost: 34.50,  category: "Dogwood Shrub" },
  { name: "Arctic Fire / Red Twig Dogwood #4",               default_unit: "ea", default_unit_cost: 30.00,  category: "Dogwood Shrub" },
  { name: "Red Twig Dogwood #10",                            default_unit: "ea", default_unit_cost: 34.50,  category: "Dogwood Shrub" },
  { name: "Burning Bush Container #4",                       default_unit: "ea", default_unit_cost: 29.50,  category: "Euonymus" },
  { name: "Gold Tide / Northern Gold Forsythia #4",          default_unit: "ea", default_unit_cost: 29.50,  category: "Forsythia" },
  { name: "Northern Gold Forsythia #10",                     default_unit: "ea", default_unit_cost: 34.50,  category: "Forsythia" },
  { name: "Show Off Sugar Baby Forsythia #4",                default_unit: "ea", default_unit_cost: 29.50,  category: "Forsythia" },
  { name: "Fothergilla #4",                                  default_unit: "ea", default_unit_cost: 36.50,  category: "Other Deciduous Shrubs" },
  { name: "Hydrangea Standard #4",                           default_unit: "ea", default_unit_cost: 33.50,  category: "Hydrangea" },
  { name: "Hydrangea Premium #4",                            default_unit: "ea", default_unit_cost: 36.50,  category: "Hydrangea" },
  { name: "Henry Garnet Itea #4",                            default_unit: "ea", default_unit_cost: 32.00,  category: "Itea" },
  { name: "Little Henry Itea #4",                            default_unit: "ea", default_unit_cost: 32.00,  category: "Itea" },
  { name: "French Lilac Container #7",                       default_unit: "ea", default_unit_cost: 31.00,  category: "Lilac" },
  { name: "French Lilac Container #10",                      default_unit: "ea", default_unit_cost: 34.00,  category: "Lilac" },
  { name: "Bloomerang / Korean / Miss Kim Lilac #4",         default_unit: "ea", default_unit_cost: 29.00,  category: "Lilac" },
  { name: "Korean / Miss Kim Lilac #10",                     default_unit: "ea", default_unit_cost: 34.00,  category: "Lilac" },
  { name: "Physocarpus #4 / #7",                             default_unit: "ea", default_unit_cost: 33.00,  category: "Physocarpus" },
  { name: "Potentilla #4",                                   default_unit: "ea", default_unit_cost: 26.50,  category: "Other Deciduous Shrubs" },
  { name: "Drift Rose #3",                                   default_unit: "ea", default_unit_cost: 28.00,  category: "Roses" },
  { name: "Shrub Rose #3",                                   default_unit: "ea", default_unit_cost: 26.50,  category: "Roses" },
  { name: "Spirea 15-18\"",                                  default_unit: "ea", default_unit_cost: 25.00,  category: "Spirea" },
  { name: "Gro-Low Sumac #3",                                default_unit: "ea", default_unit_cost: 24.00,  category: "Other Deciduous Shrubs" },
  { name: "Burkwood / Juddi Viburnum #7",                    default_unit: "ea", default_unit_cost: 38.50,  category: "Viburnum" },
  { name: "Chicago Lustre / Mariesii / Mohican Viburnum #10",default_unit: "ea", default_unit_cost: 35.00,  category: "Viburnum" },
  { name: "Weigela #4",                                      default_unit: "ea", default_unit_cost: 28.50,  category: "Weigela" },
  { name: "Butterfly Bush #3",                               default_unit: "ea", default_unit_cost: 26.50,  category: "Other Deciduous Shrubs" },
  { name: "Clethra #4",                                      default_unit: "ea", default_unit_cost: 36.00,  category: "Other Deciduous Shrubs" },
  { name: "Hypericum #4",                                    default_unit: "ea", default_unit_cost: 29.50,  category: "Other Deciduous Shrubs" },
  { name: "Rose of Sharon #7",                               default_unit: "ea", default_unit_cost: 42.50,  category: "Other Deciduous Shrubs" },
  { name: "Fineline Buckthorn #5/#7",                        default_unit: "ea", default_unit_cost: 36.50,  category: "Other Deciduous Shrubs" },
  { name: "Witchhazel #7",                                   default_unit: "ea", default_unit_cost: 37.00,  category: "Other Deciduous Shrubs" },
  // ── BROADLEAF EVERGREENS ──────────────────────────────────────────────
  { name: "Azalea #3",                                       default_unit: "ea", default_unit_cost: 40.00,  category: "Azalea" },
  { name: "Green Velvet / Green Mountain Boxwood 12-15\"",   default_unit: "ea", default_unit_cost: 36.50,  category: "Boxwood" },
  { name: "Boxwood 15-18\"",                                 default_unit: "ea", default_unit_cost: 44.00,  category: "Boxwood" },
  { name: "Boxwood 18-21\"",                                 default_unit: "ea", default_unit_cost: 54.00,  category: "Boxwood" },
  { name: "Boxwood 18-24\"",                                 default_unit: "ea", default_unit_cost: 60.00,  category: "Boxwood" },
  { name: "Boxwood Pyramidal 18\"",                          default_unit: "ea", default_unit_cost: 58.00,  category: "Boxwood" },
  { name: "Boxwood Pyramidal 24\"",                          default_unit: "ea", default_unit_cost: 98.00,  category: "Boxwood" },
  { name: "Boxwood Pyramidal 24-30\"",                       default_unit: "ea", default_unit_cost: 120.00, category: "Boxwood" },
  { name: "Boxwood Pyramidal 30-36\"",                       default_unit: "ea", default_unit_cost: 140.00, category: "Boxwood" },
  { name: "Green Gem Boxwood 12-15\"",                       default_unit: "ea", default_unit_cost: 36.50,  category: "Boxwood" },
  { name: "Green Gem Boxwood 15-18\"",                       default_unit: "ea", default_unit_cost: 44.00,  category: "Boxwood" },
  { name: "Blue Holly #5",                                   default_unit: "ea", default_unit_cost: 68.00,  category: "Holly" },
  { name: "Ilex Glabra Strongbox / Shamrock #4",             default_unit: "ea", default_unit_cost: 40.00,  category: "Holly" },
  { name: "Michigan Holly #4",                               default_unit: "ea", default_unit_cost: 37.00,  category: "Holly" },
  { name: "Gaiety / Gold Splash Euonymus #3",                default_unit: "ea", default_unit_cost: 35.50,  category: "Other Deciduous Shrubs" },
  { name: "Rhododendron 15-18\"",                            default_unit: "ea", default_unit_cost: 46.00,  category: "Rhododendron" },
  { name: "Rhododendron 18-24\"",                            default_unit: "ea", default_unit_cost: 64.00,  category: "Rhododendron" },
  { name: "Rhododendron 24-30\"",                            default_unit: "ea", default_unit_cost: 76.00,  category: "Rhododendron" },
  { name: "PJM Rhododendron #3",                             default_unit: "ea", default_unit_cost: 48.00,  category: "Rhododendron" },
  { name: "PJM Rhododendron #5",                             default_unit: "ea", default_unit_cost: 68.00,  category: "Rhododendron" },
  // ── SPECIALTY / ACCENT TREES ──────────────────────────────────────────
  { name: "Dawyck Beech 7-8'",                               default_unit: "ea", default_unit_cost: 295.00, category: "Beech" },
  { name: "Purple Fountain Beech 1.5\"",                     default_unit: "ea", default_unit_cost: 330.00, category: "Beech" },
  { name: "Riversii Beech #25",                              default_unit: "ea", default_unit_cost: 295.00, category: "Beech" },
  { name: "Tri-Color Beech 7-8'",                            default_unit: "ea", default_unit_cost: 285.00, category: "Beech" },
  { name: "Tri-Color Beech 1.5\"",                           default_unit: "ea", default_unit_cost: 435.00, category: "Beech" },
  { name: "Tri-Color Beech 2\"",                             default_unit: "ea", default_unit_cost: 485.00, category: "Beech" },
  { name: "Japanese Maple (Green) 24-30\"",                  default_unit: "ea", default_unit_cost: 178.00, category: "Japanese Maple" },
  { name: "Japanese Maple (Green) 30-36\"",                  default_unit: "ea", default_unit_cost: 220.00, category: "Japanese Maple" },
  { name: "Japanese Maple Weeping Cutleaf 18-24\"",          default_unit: "ea", default_unit_cost: 148.00, category: "Japanese Maple" },
  { name: "Japanese Maple Weeping Cutleaf 24-30\"",          default_unit: "ea", default_unit_cost: 178.00, category: "Japanese Maple" },
  { name: "Japanese Maple Weeping Cutleaf #10",              default_unit: "ea", default_unit_cost: 220.00, category: "Japanese Maple" },
  { name: "Japanese Maple Weeping Cutleaf #15",              default_unit: "ea", default_unit_cost: 330.00, category: "Japanese Maple" },
  { name: "Japanese Maple Weeping Cutleaf #25",              default_unit: "ea", default_unit_cost: 395.00, category: "Japanese Maple" },
  { name: "Bloodgood Japanese Maple 5-6'",                   default_unit: "ea", default_unit_cost: 235.00, category: "Japanese Maple" },
  { name: "Bloodgood Japanese Maple 6'",                     default_unit: "ea", default_unit_cost: 270.00, category: "Japanese Maple" },
  { name: "Bloodgood Japanese Maple 6-7'",                   default_unit: "ea", default_unit_cost: 315.00, category: "Japanese Maple" },
  { name: "Bloodgood Japanese Maple 7-8'",                   default_unit: "ea", default_unit_cost: 415.00, category: "Japanese Maple" },
  { name: "Jane Magnolia 5'",                                default_unit: "ea", default_unit_cost: 155.00, category: "Magnolia" },
  { name: "Jane Magnolia 6'",                                default_unit: "ea", default_unit_cost: 185.00, category: "Magnolia" },
  { name: "Star Magnolia 5'",                                default_unit: "ea", default_unit_cost: 165.00, category: "Magnolia" },
  { name: "Scotch Pine Poodle Bonsai 4-5'",                  default_unit: "ea", default_unit_cost: 395.00, category: "Bonsai & Topiaries" },
  { name: "Scotch Pine Poodle Bonsai 5-6'",                  default_unit: "ea", default_unit_cost: 455.00, category: "Bonsai & Topiaries" },
  { name: "Oriental Pom Pom Juniper #10",                    default_unit: "ea", default_unit_cost: 335.00, category: "Bonsai & Topiaries" },
  { name: "Pom Pom Juniper #7",                              default_unit: "ea", default_unit_cost: 250.00, category: "Bonsai & Topiaries" },
  { name: "Poodle 2-Tier Juniper #5",                        default_unit: "ea", default_unit_cost: 175.00, category: "Bonsai & Topiaries" },
  { name: "Spiral Juniper #5",                               default_unit: "ea", default_unit_cost: 210.00, category: "Bonsai & Topiaries" },
  { name: "Spiral Juniper #10",                              default_unit: "ea", default_unit_cost: 295.00, category: "Bonsai & Topiaries" },
  // ── PERENNIALS ────────────────────────────────────────────────────────
  { name: "Happy Returns Daylily #2",                        default_unit: "ea", default_unit_cost: 12.25,  category: "Daylily" },
  { name: "Little Grapette Daylily #2",                      default_unit: "ea", default_unit_cost: 11.25,  category: "Daylily" },
  { name: "Mauna Loa Daylily #2",                            default_unit: "ea", default_unit_cost: 12.25,  category: "Daylily" },
  { name: "Pardon Me Daylily #2",                            default_unit: "ea", default_unit_cost: 12.25,  category: "Daylily" },
  { name: "Passionate Return Daylily #2",                    default_unit: "ea", default_unit_cost: 12.25,  category: "Daylily" },
  { name: "Ruby Spider Daylily #2",                          default_unit: "ea", default_unit_cost: 12.25,  category: "Daylily" },
  { name: "Stella D'oro Daylily #2",                         default_unit: "ea", default_unit_cost: 11.25,  category: "Daylily" },
  { name: "Strawberry Candy Daylily #2",                     default_unit: "ea", default_unit_cost: 12.25,  category: "Daylily" },
  { name: "Happy Returns Daylily 1gal",                      default_unit: "ea", default_unit_cost: 7.75,   category: "Daylily" },
  { name: "Stella D'oro Daylily 1gal",                       default_unit: "ea", default_unit_cost: 7.75,   category: "Daylily" },
  { name: "DWF Fountain Grass Hameln 1gal",                  default_unit: "ea", default_unit_cost: 8.50,   category: "Ornamental Grasses" },
  { name: "Karl Foerster Reedgrass 1gal",                    default_unit: "ea", default_unit_cost: 8.50,   category: "Ornamental Grasses" },
  { name: "Prairie Dropseed 1gal",                           default_unit: "ea", default_unit_cost: 8.50,   category: "Ornamental Grasses" },
  { name: "Carex Pensylvanica 1gal",                         default_unit: "ea", default_unit_cost: 8.75,   category: "Ornamental Grasses" },
  { name: "Carex Ice Dance 1gal",                            default_unit: "ea", default_unit_cost: 8.75,   category: "Ornamental Grasses" },
  { name: "Hosta Francee #2",                                default_unit: "ea", default_unit_cost: 12.75,  category: "Hosta" },
  { name: "Hosta Frances Williams #2",                       default_unit: "ea", default_unit_cost: 12.75,  category: "Hosta" },
  { name: "Hosta Gold Standard #2",                          default_unit: "ea", default_unit_cost: 12.75,  category: "Hosta" },
  { name: "Hosta Golden Tiara #2",                           default_unit: "ea", default_unit_cost: 12.75,  category: "Hosta" },
  { name: "Hosta Halcyon #2",                                default_unit: "ea", default_unit_cost: 12.75,  category: "Hosta" },
  { name: "Hosta Krossa Regal #2",                           default_unit: "ea", default_unit_cost: 12.75,  category: "Hosta" },
  { name: "Hosta Royal Standard #2",                         default_unit: "ea", default_unit_cost: 12.75,  category: "Hosta" },
  { name: "Hosta Sum & Substance #2",                        default_unit: "ea", default_unit_cost: 12.75,  category: "Hosta" },
  { name: "Hosta Autumn Frost Premium #2",                   default_unit: "ea", default_unit_cost: 15.00,  category: "Hosta" },
  { name: "Hosta Blue Angel Premium #2",                     default_unit: "ea", default_unit_cost: 15.00,  category: "Hosta" },
  { name: "Hosta June Premium #2",                           default_unit: "ea", default_unit_cost: 15.00,  category: "Hosta" },
  { name: "Hosta Liberty Premium #2",                        default_unit: "ea", default_unit_cost: 15.00,  category: "Hosta" },
  { name: "Hosta Patriot Premium #2",                        default_unit: "ea", default_unit_cost: 15.00,  category: "Hosta" },
  { name: "Assorted Perennials #2",                          default_unit: "ea", default_unit_cost: 11.75,  category: "Assorted Perennials" },
  { name: "Premium Introductions #2",                        default_unit: "ea", default_unit_cost: 13.25,  category: "Premium Perennials" },
  { name: "Ajuga Ground Cover 32/flat",                      default_unit: "flat", default_unit_cost: 56.00, category: "Ground Cover" },
  { name: "Euonymus Coloratus Ground Cover 32/flat",         default_unit: "flat", default_unit_cost: 56.00, category: "Ground Cover" },
  { name: "Myrtle Ground Cover 32/flat",                     default_unit: "flat", default_unit_cost: 56.00, category: "Ground Cover" },
  { name: "Pachysandra Ground Cover 32/flat",                default_unit: "flat", default_unit_cost: 56.00, category: "Ground Cover" },
  { name: "Thorndale Ivy 10/flat",                           default_unit: "flat", default_unit_cost: 20.00, category: "Ground Cover" },
  { name: "Clematis #1",                                     default_unit: "ea", default_unit_cost: 22.50,  category: "Assorted Perennials" },
  // ── SUPPLIES ──────────────────────────────────────────────────────────
  { name: "Canadian Peat 1.0 cu ft",                         default_unit: "bag", default_unit_cost: 12.00, category: "Peat & Planting Mix" },
  { name: "Canadian Peat 3.8 cu ft",                         default_unit: "bag", default_unit_cost: 24.00, category: "Peat & Planting Mix" },
  { name: "Planting Mix 1.5 cu ft",                          default_unit: "bag", default_unit_cost: 8.50,  category: "Peat & Planting Mix" },
  { name: "Planting Mix 3 cu ft",                            default_unit: "bag", default_unit_cost: 14.50, category: "Peat & Planting Mix" },
  { name: "Bulk Screened Hardwood Bark",                     default_unit: "yd",  default_unit_cost: 34.00, category: "Mulch & Bark" },
  { name: "Topsoil (Bulk)",                                  default_unit: "yd",  default_unit_cost: 29.00, category: "Soil & Topsoil" },
  { name: "Black Diamond Edging 20' Length",                 default_unit: "ea",  default_unit_cost: 17.25, category: "Edging" },
  { name: "Black Diamond Edging 90° Corner",                 default_unit: "ea",  default_unit_cost: 6.25,  category: "Edging" },
  { name: "Black Diamond Edging Stake",                      default_unit: "ea",  default_unit_cost: 3.00,  category: "Edging" },
  { name: "Black Diamond Edging Stake Kit",                  default_unit: "ea",  default_unit_cost: 6.00,  category: "Edging" },
  { name: "Dewitt Weed Barrier Pro-5 3x250'",                default_unit: "roll", default_unit_cost: 155.00, category: "Weed Barrier" },
  { name: "Dewitt Weed Barrier Pro-5 4x250'",                default_unit: "roll", default_unit_cost: 225.00, category: "Weed Barrier" },
  { name: "Dewitt Weed Barrier Pro-5 6x250'",                default_unit: "roll", default_unit_cost: 275.00, category: "Weed Barrier" },
  { name: "Heavy Duty Tarp 8x10'",                           default_unit: "ea",  default_unit_cost: 66.00, category: "Tarps & Miscellaneous" },
  { name: "Heavy Duty Tarp 10x12'",                          default_unit: "ea",  default_unit_cost: 90.00, category: "Tarps & Miscellaneous" },
  { name: "Heavy Duty Tarp 10x18'",                          default_unit: "ea",  default_unit_cost: 110.00, category: "Tarps & Miscellaneous" },
  { name: "Heavy Duty Tarp 12x25'",                          default_unit: "ea",  default_unit_cost: 165.00, category: "Tarps & Miscellaneous" },
];

export async function GET() {
  const supabase = supabaseAdmin();

  // Fetch all categories to build name→id map
  const { data: cats, error: catErr } = await supabase
    .from("material_categories")
    .select("id, name");
  if (catErr) return NextResponse.json({ error: catErr.message }, { status: 500 });

  const catMap = new Map<string, string>();
  for (const c of cats ?? []) catMap.set(c.name.trim(), c.id);

  // Resolve company_id
  const { data: co } = await supabase.from("bids").select("company_id").not("company_id", "is", null).limit(1).maybeSingle();
  const company_id = co?.company_id ?? null;

  // Clear existing catalog entries (from Kluck vendor only, if re-running)
  await supabase.from("materials_catalog").delete().eq("vendor", "Kluck Nursery");

  const rows = MATERIALS.map(m => ({
    name: m.name,
    default_unit: m.default_unit,
    default_unit_cost: m.default_unit_cost,
    vendor: "Kluck Nursery",
    is_active: true,
    category_id: catMap.get(m.category) ?? null,
    ...(company_id ? {} : {}), // company_id not on this table
  }));

  // Warn about unmapped categories
  const missing = [...new Set(MATERIALS.filter(m => !catMap.has(m.category)).map(m => m.category))];

  // Batch insert in chunks of 50
  let inserted = 0;
  for (let i = 0; i < rows.length; i += 50) {
    const chunk = rows.slice(i, i + 50);
    const { error } = await supabase.from("materials_catalog").insert(chunk);
    if (error) return NextResponse.json({ error: error.message, at: i }, { status: 500 });
    inserted += chunk.length;
  }

  return NextResponse.json({ ok: true, inserted, missing_categories: missing });
}
